import numpy as np
arr1 = np.array([(4,6,2),(7,9,2)])
arr2 = np.array([(10,6,9),(2,9,2)])
#vector maths
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.power(arr1,arr2))
print(np.sqrt(arr1))
print(np.log(arr2))
print(np.sin(arr1))
print(np.ceil(arr1))
print(np.abs(arr2))
print(np.floor(arr1))
print(np.round(arr2))